// File types
const ENABLED_APP = "ENABLED_APP";
const CLOSED_FILE = "CLOSED_FILE";
const DISABLED_APP = "DISABLED_APP";
const CHANGED_BLOB = "CHANGED_BLOB";
const UPLOADED_FILE = "UPLOADED_FILE";

export const fileTypes = {
  ENABLED_APP,
  CLOSED_FILE,
  DISABLED_APP,
  CHANGED_BLOB,
  UPLOADED_FILE,
};

// Top Navigation
const CLOSED_DROPDOWN = "CLOSED_DROPDOWN";
const EXPANDED_DROPDOWN = "EXPANDED_DROPDOWN";

export const topNavigationTypes = {
  CLOSED_DROPDOWN,
  EXPANDED_DROPDOWN,
};

// Modals
const CLOSED_MODAL = "CLOSED_MODAL";
const EXPANDED_MODAL = "EXPANDED_MODAL";
const CLOSED_MODAL_EXPANSION = "CLOSED_MODAL_EXPANSION";
const EXPANDED_MODAL_EXPANSION = "OPENED_MODAL_EXPANSION";

export const modalTypes = {
  CLOSED_MODAL,
  EXPANDED_MODAL,
  CLOSED_MODAL_EXPANSION,
  EXPANDED_MODAL_EXPANSION,
};
